on:
  push:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: biomejs/setup-biome@v2
        with:
          version: latest
      - uses: actions/checkout@v4
      - name: Lint and check formatting
        run: biome ci .
